#---------------------------------- dataset -----------------------------------------#
dataset: uci
n_feature: 9
len_sw: 128
n_class: 6

# target_domain: 0
n_domains: 5
n_target_domains: 1

#------------------------------------ training -------------------------------------------#
# batch_size: 128
n_epoch: 100
seed: 10
interval_validate: 20
out_path: './logs'
save_model: True

#-------------------------------------- model -------------------------------------------#
model: 'cnn'
res: False
resume: False

#---------------------------------- optimizer -------------------------------------------#
lr: 1e-3
wd: 5e-4
lr_decrease_rate: 0.5
lr_decrease_interval: 20
